// Secure bridge: the only surface the renderer can touch.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("sentinel", {
  sysinfo: () => ipcRenderer.invoke("sysinfo"),
  run: (id, cmd, cwd) => ipcRenderer.invoke("run", { id, cmd, cwd }),
  kill: (id) => ipcRenderer.invoke("kill", id),
  which: (name) => ipcRenderer.invoke("which", name),
  agentExec: (command, cwd, timeout, autopass) => ipcRenderer.invoke("agent:exec", { command, cwd, timeout, autopass }),
  toolInstall: (id, install) => ipcRenderer.invoke("tool:install", { id, install }),
  onToolInstallData: (cb) => ipcRenderer.on("tool:install:data", (_e, d) => cb(d)),
  ollama: (path, body) => ipcRenderer.invoke("ollama", { path, body }),
  ollamaStream: (id, body) => ipcRenderer.invoke("ollama:stream", { id, body }),
  ollamaCancel: (id) => ipcRenderer.invoke("ollama:cancel", id),
  onOllamaToken: (cb) => ipcRenderer.on("ollama:token", (_e, d) => cb(d)),
  // Claude (Anthropic) cloud engine — same streaming contract as Ollama
  claudeStream: (id, body, apiKey) => ipcRenderer.invoke("claude:stream", { id, body, apiKey }),
  claudeCancel: (id) => ipcRenderer.invoke("claude:cancel", id),
  onClaudeToken: (cb) => ipcRenderer.on("claude:token", (_e, d) => cb(d)),
  // Any model via an OpenAI-compatible API — same streaming contract as Ollama/Claude
  apiStream: (id, body, base, apiKey, model) => ipcRenderer.invoke("api:stream", { id, body, base, apiKey, model }),
  apiCancel: (id) => ipcRenderer.invoke("api:cancel", id),
  onApiToken: (cb) => ipcRenderer.on("api:token", (_e, d) => cb(d)),
  // enterprise governance: usage ledger + compliance bundle
  govIdentity: () => ipcRenderer.invoke("gov:identity"),
  govUsageAppend: (rec) => ipcRenderer.invoke("gov:usage:append", rec),
  govUsageReport: (opts) => ipcRenderer.invoke("gov:usage:report", opts),
  govComplianceBuild: (opts) => ipcRenderer.invoke("gov:compliance:build", opts),
  govComplianceVerify: (bundle, signingKey) => ipcRenderer.invoke("gov:compliance:verify", { bundle, signingKey }),
  openExternal: (url) => ipcRenderer.invoke("openExternal", url),
  winMin: () => ipcRenderer.invoke("win:minimize"),
  winMax: () => ipcRenderer.invoke("win:maximize"),
  winClose: () => ipcRenderer.invoke("win:close"),
  checkUpdate: () => ipcRenderer.invoke("app:checkUpdate"),
  noBootAnim: (() => { try { return process.env.SENTINEL_NO_BOOT === "1" || process.argv.includes("--no-boot-anim"); } catch (_) { return false; } })(),
  gmailOAuth: (creds) => ipcRenderer.invoke("gmail:oauth", creds),
  gmailRefresh: (arg) => ipcRenderer.invoke("gmail:refresh", arg),
  netGet: (opts) => ipcRenderer.invoke("net:get", opts),
  onWinState: (cb) => ipcRenderer.on("win:state", (_e, max) => cb(max)),
  httpReq: (opts) => ipcRenderer.invoke("http:request", opts),
  cveSearch: (q) => ipcRenderer.invoke("cve:search", q),
  resultsList: () => ipcRenderer.invoke("results:list"),
  resultsRead: (name) => ipcRenderer.invoke("results:read", name),
  resultsReveal: () => ipcRenderer.invoke("results:reveal"),
  openFolder: () => ipcRenderer.invoke("dialog:openFolder"),
  openFile: (filters) => ipcRenderer.invoke("dialog:openFile", filters),
  vmDeps: () => ipcRenderer.invoke("vm:deps"),
  vmList: () => ipcRenderer.invoke("vm:list"),
  vmCreate: (opts) => ipcRenderer.invoke("vm:create", opts),
  vmBuildSentinel: (opts) => ipcRenderer.invoke("vm:buildSentinel", opts),
  onVmBuildLog: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on("vm:buildLog", h); return () => ipcRenderer.removeListener("vm:buildLog", h); },
  vmUpdate: (id, patch) => ipcRenderer.invoke("vm:update", { id, patch }),
  vmDelete: (id, deleteDisk) => ipcRenderer.invoke("vm:delete", { id, deleteDisk }),
  vmStart: (id) => ipcRenderer.invoke("vm:start", { id }),
  vmStop: (id, force) => ipcRenderer.invoke("vm:stop", { id, force }),
  vmReset: (id) => ipcRenderer.invoke("vm:reset", { id }),
  vmKey: (id, keys) => ipcRenderer.invoke("vm:key", { id, keys }),
  vmScreendump: (id) => ipcRenderer.invoke("vm:screendump", { id }),
  vmMouse: (id, x, y, down, up) => ipcRenderer.invoke("vm:mouse", { id, x, y, down, up }),
  onVmExit: (cb) => ipcRenderer.on("vm:exit", (_e, d) => cb(d)),
  fsList: (dir) => ipcRenderer.invoke("fs:list", dir),
  fsRead: (file) => ipcRenderer.invoke("fs:read", file),
  fsWrite: (file, data) => ipcRenderer.invoke("fs:write", { file, data }),
  fsMkfile: (dir, name) => ipcRenderer.invoke("fs:mkfile", { dir, name }),
  dnsLookup: (host) => ipcRenderer.invoke("dns:lookup", host),
  whois: (query) => ipcRenderer.invoke("whois:query", query),
  tlsCert: (host, port) => ipcRenderer.invoke("tls:cert", { host, port }),
  subdomains: (domain) => ipcRenderer.invoke("subdomains:find", domain),
  gitClone: (url, token) => ipcRenderer.invoke("git:clone", { url, token }),
  gitStatus: (dir) => ipcRenderer.invoke("git:status", dir),
  gitPush: (opts) => ipcRenderer.invoke("git:push", opts),
  gitPull: (dir, token) => ipcRenderer.invoke("git:pull", { dir, token }),
  gitBranches: (dir) => ipcRenderer.invoke("git:branches", dir),
  gitCheckout: (dir, branch) => ipcRenderer.invoke("git:checkout", { dir, branch }),
  gitCheckoutNew: (dir, branch) => ipcRenderer.invoke("git:checkoutNew", { dir, branch }),
  gitLog: (dir) => ipcRenderer.invoke("git:log", dir),
  gitDiff: (dir, file) => ipcRenderer.invoke("git:diff", { dir, file }),
  ghRepos: (token) => ipcRenderer.invoke("github:repos", token),
  ghIssues: (dir, token) => ipcRenderer.invoke("github:issues", { dir, token }),
  ghCreateIssue: (opts) => ipcRenderer.invoke("github:createIssue", opts),
  ghCreatePR: (opts) => ipcRenderer.invoke("github:createPR", opts),
  ghComment: (opts) => ipcRenderer.invoke("github:comment", opts),
  ghCreateGist: (opts) => ipcRenderer.invoke("github:createGist", opts),
  scanPorts: (opts) => ipcRenderer.invoke("scan:ports", opts),
  scanCancel: (id) => ipcRenderer.invoke("scan:cancel", id),
  onScanHit: (cb) => ipcRenderer.on("scan:hit", (_e, d) => cb(d)),
  onScanProgress: (cb) => ipcRenderer.on("scan:progress", (_e, d) => cb(d)),
  onScanDone: (cb) => ipcRenderer.on("scan:done", (_e, d) => cb(d)),
  fuzzDirs: (opts) => ipcRenderer.invoke("fuzz:dirs", opts),
  fuzzCancel: (id) => ipcRenderer.invoke("fuzz:cancel", id),
  onFuzzHit: (cb) => ipcRenderer.on("fuzz:hit", (_e, d) => cb(d)),
  onFuzzProgress: (cb) => ipcRenderer.on("fuzz:progress", (_e, d) => cb(d)),
  onFuzzDone: (cb) => ipcRenderer.on("fuzz:done", (_e, d) => cb(d)),
  onRunData: (cb) => ipcRenderer.on("run:data", (_e, d) => cb(d)),
  onRunEnd: (cb) => ipcRenderer.on("run:end", (_e, d) => cb(d)),
  ptySpawn: (cols, rows) => ipcRenderer.invoke("pty:spawn", { cols, rows }),
  ptyWrite: (id, data) => ipcRenderer.invoke("pty:write", { id, data }),
  ptyResize: (id, cols, rows) => ipcRenderer.invoke("pty:resize", { id, cols, rows }),
  ptyKill: (id) => ipcRenderer.invoke("pty:kill", { id }),
  onPtyData: (cb) => ipcRenderer.on("pty:data", (_e, d) => cb(d)),
  onPtyExit: (cb) => ipcRenderer.on("pty:exit", () => cb()),
  mcpConnect: (cfg) => ipcRenderer.invoke("mcp:connect", cfg),
  mcpList: () => ipcRenderer.invoke("mcp:list"),
  mcpCall: (server, tool, args) => ipcRenderer.invoke("mcp:call", { server, tool, args }),
  mcpReadResource: (server, uri) => ipcRenderer.invoke("mcp:readResource", { server, uri }),
  mcpGetPrompt: (server, name, args) => ipcRenderer.invoke("mcp:getPrompt", { server, name, args }),
  mcpSampleModel: (model) => ipcRenderer.invoke("mcp:sampleModel", model),
  mcpDisconnect: (name) => ipcRenderer.invoke("mcp:disconnect", name),
  mcpStatus: () => ipcRenderer.invoke("mcp:status"),
});
